"""added customer relation to sales

Revision ID: 0b581221f21d
Revises: f0d2518f2a05
Create Date: 2026-05-16 14:30:22.291991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b581221f21d'
down_revision: Union[str, Sequence[str], None] = 'f0d2518f2a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'customer_id')
    # ### end Alembic commands ###
